module.exports = {
    NETWORK: 'NETWORK',
    NETWORKED: 'NETWORKED',
    GOT_NETWORKS: 'GOT_NETWORKS',

    GOT_CURRENT_USER: 'GOT_CURRENT_USER',
    GOT_USERS: 'GOT_USERS',

    FOLLOW: 'FOLLOW',
    FOLLOWED: 'FOLLOWED',

    UNFOLLOW: 'UNFOLLOW',
    UNFOLLOWED: 'UNFOLLOWED'
};
